spring:
  aop:
    proxy-target-class: true

preprocessing:
  preprocessors:
    - ch.uzh.seal.BLogDiff.preprocessing.PreprocessorMaven
    - ch.uzh.seal.BLogDiff.preprocessing.PreprocessorTravisCI
  replacement: "<...>"

analysis:
  inputDirGithub: "C:\\Data\\BA\\outputgh\\"
  inputDirTravis: "C:\\Data\\BA\\outputtravis\\"
  outputDir: "C:\\Data\\UZH\\BA\\analysis\\"


