spring:
  aop:
    proxy-target-class: true

spring.datasource.driver-class-name: org.mariadb.jdbc.Driver
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
spring.jpa.hibernate.ddl-auto: update
SPRING.DATASOURCE.URL: "jdbc:mysql://localhost:3306/blogdiff"
SPRING.DATASOURCE.USERNAME: "noah"
SPRING.DATASOURCE.PASSWORD: "noahsPW"

GUI.HOST: "http://localhost:4200"
GUI.USER: "admin"
GUI.PASSWORD: "password"

preprocessing:
  preprocessors:
    - ch.uzh.seal.BLogDiff.preprocessing.PreprocessorMaven
    - ch.uzh.seal.BLogDiff.preprocessing.PreprocessorTravisCI
  replacement: "<...>"

analysis:
  inputDirGithub: "C:\\Data\\BA\\outputgh\\"
  inputDirTravis: "C:\\Data\\BA\\outputtravis\\"
  outputDir: "C:\\Data\\UZH\\BA\\analysis\\"


